name = "NsightCompute"
uuid = "5f16bdfc-5065-4f60-a755-c8949118381f"
version = "1.0.0-DEV"
authors = ["singularitti <singularitti@outlook.com> and contributors"]

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
StructTypes = "856f2bd8-1eba-4b0a-8007-ebc267875bd4"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
CSV = "0.10.15"
DataFrames = "1.7.0"
JSON3 = "1.14.3"
StructTypes = "1.11.0"
Tables = "1.12.1"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
